package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-07T16:10:24.283+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "HospitalSMS", 
                  wsdlLocation = "http://172.31.10.47:8003/HospitalSMS.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class HospitalSMS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "HospitalSMS");
    public final static QName HospitalSMSSoap12 = new QName("http://tempuri.org/", "HospitalSMSSoap12");
    public final static QName HospitalSMSSoap = new QName("http://tempuri.org/", "HospitalSMSSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://172.31.10.47:8003/HospitalSMS.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HospitalSMS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.31.10.47:8003/HospitalSMS.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HospitalSMS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HospitalSMS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HospitalSMS() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HospitalSMS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HospitalSMS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HospitalSMS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns HospitalSMSSoap
     */
    @WebEndpoint(name = "HospitalSMSSoap12")
    public HospitalSMSSoap getHospitalSMSSoap12() {
        return super.getPort(HospitalSMSSoap12, HospitalSMSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HospitalSMSSoap
     */
    @WebEndpoint(name = "HospitalSMSSoap12")
    public HospitalSMSSoap getHospitalSMSSoap12(WebServiceFeature... features) {
        return super.getPort(HospitalSMSSoap12, HospitalSMSSoap.class, features);
    }
    /**
     *
     * @return
     *     returns HospitalSMSSoap
     */
    @WebEndpoint(name = "HospitalSMSSoap")
    public HospitalSMSSoap getHospitalSMSSoap() {
        return super.getPort(HospitalSMSSoap, HospitalSMSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HospitalSMSSoap
     */
    @WebEndpoint(name = "HospitalSMSSoap")
    public HospitalSMSSoap getHospitalSMSSoap(WebServiceFeature... features) {
        return super.getPort(HospitalSMSSoap, HospitalSMSSoap.class, features);
    }

}
