package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-08-14T16:07:08.103+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "MobileWardSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MobileWardSoap {

    /**
     * 获取病人的病历文件另存的html的格式的文件的路径,参数：病人ID，住院次数，文件顺序号
     */
    @WebResult(name = "GetPatientFilePathResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPatientFilePath", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPatientFilePath")
    @WebMethod(operationName = "GetPatientFilePath", action = "http://tempuri.org/GetPatientFilePath")
    @ResponseWrapper(localName = "GetPatientFilePathResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPatientFilePathResponse")
    public java.lang.String getPatientFilePath(
        @WebParam(name = "patientID", targetNamespace = "http://tempuri.org/")
        java.lang.String patientID,
        @WebParam(name = "visitID", targetNamespace = "http://tempuri.org/")
        java.lang.String visitID,
        @WebParam(name = "fileNo", targetNamespace = "http://tempuri.org/")
        java.lang.String fileNo
    );
}
